baseURL = 'https://learn-dh-software-dev.org/'
languageCode = 'en-us'
title = 'DHTech - Education & Training WG'
theme = 'ananke'
pagination.pagerSize = 3
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    custom_css = ["custom.css"]
    recent_posts_number = 4
    toc = true

[taxonomies]
    status = "status"
    pathway = "pathways"
    tag = "tags"

[menu]

  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 1
    identifier = "about"

  [[menu.main]]
    name = "Lessons"
    url = "/lessons/"
    weight = 2
    identifier = "lessons"

  [[menu.main]]
    name = "Contribute"
    weight = 3
    identifier = "contribute"

  [[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    parent = "contribute"
    weight = 1
    
  [[menu.main]]
    name = "Author Guidelines"
    url = "/contribute/author-guidelines/"
    parent = "contribute"
    weight = 2

  [[menu.main]]
    name = "Reviewer Guidelines"
    url = "/contribute/reviewer-guidelines/"
    parent = "contribute"
    weight = 3

